### PR TITLE
Enable blacklisting rotated refresh tokens

### PR DESCRIPTION
**Pull request by jmorel**
Enables the blacklisting of rotated refresh tokens.

Since the rotation was already activated and the blacklist app already installed, the only thing missing was the `BLACKLIST_AFTER_ROTATION` option, now set to True.

The documentation recommends setting up a cron job that cleans up expired blacklisted tokens. I took inspiration from the add-account operator and added an operator that cleans the token once everyday.

Related documentation:
* https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#rotate-refresh-tokens
* https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html

# To test this PR

1. patch the backend with the following diff and launch it

```diff
diff --git a/backend/backend/celery.py b/backend/backend/celery.py
index 8a7fc7bc..56d2dca4 100644
--- a/backend/backend/celery.py
+++ b/backend/backend/celery.py
@@ -38,7 +38,7 @@ def setup_periodic_tasks(sender, **kwargs):

     from users.tasks import flush_expired_tokens

-    period = int(os.environ.get('FLUSH_EXPIRED_TOKENS_TASK_PERIOD', 24 * 3600))
+    period = int(os.environ.get('FLUSH_EXPIRED_TOKENS_TASK_PERIOD', 60))
     sender.add_periodic_task(period, flush_expired_tokens.s(), queue='scheduler',
                              name='flush expired tokens')

diff --git a/backend/backend/settings/deps/restframework.py b/backend/backend/settings/deps/restframework.py
index d38155e4..23cc0f1f 100644
--- a/backend/backend/settings/deps/restframework.py
+++ b/backend/backend/settings/deps/restframework.py
@@ -29,8 +29,8 @@ REST_FRAMEWORK = {
 }

 SIMPLE_JWT = {
-    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('ACCESS_TOKEN_LIFETIME', 24*60))),
-    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('REFRESH_TOKEN_LIFETIME', 24*60*7))),
+    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=2),
+    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=10),
     'ROTATE_REFRESH_TOKENS': True,
     'AUTH_HEADER_TYPES': ('JWT',),
     'BLACKLIST_AFTER_ROTATION': True,
``` 
2. launch the frontend, and click around for a minute. You should see multiple calls to `/user/refresh`
3. open a shell in the backend and execute `python manage.py shell`
4. execute the following python script which should return a queryset with multiple tokens in it
```python 
from rest_framework_simplejwt.token_blacklist.models import BlacklistedToken
BlacklistedToken.objects.all()
```
5. then run our flush command, which would result in no blacklisted tokens (`BlacklistedToken.objects.all()` returns an empty queryset)
```python
from users.tasks import flush_expired_tokens
flush_expired_tokens()
BlacklistedToken.objects.all()
```
6. Then click a few more times in the frontend and wait for the periodic task to run. You can then check that there are no more blacklisted tokens.

### CODE REVIEW

**Comment by Kelvin-M** [comment]
Would it be easier to setup a schedule celery task which does something like : 
`AccessToken.objects.filter(refresh_token__isnull=True, expires__lt=datetime.now()).delete()
` here : 
https://github.com/SubstraFoundation/substra-backend/blob/master/backend/backend/celery.py

**Comment by jmorel** [comment]
@Kelvin-M done !

**Comment by Kelvin-M** [comment]
@jmorel  Nice work, do you have a procedure to test it ?

**Comment by jmorel** [comment]
@Kelvin-M I updated the description with a test procedure. It's a bit tedious sorry for that. It allowed me to find a bug though, so 👍

**Comment by jmorel** [comment]
⚠️  It appears the `ignore_result=True` was hiding a pretty big issue : 
```
[2020-04-02 09:46:17,548: ERROR/MainProcess] Pool callback raised exception: OperationalError('could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to
server: Cannot assign requested address\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/request.py", line 528, in on_failure
    store_result=self.store_errors,
  File "/usr/local/lib/python3.6/dist-packages/celery/backends/base.py", line 160, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/dist-packages/celery/backends/base.py", line 407, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_celery_results/backends/database.py", line 38, in _store_result
    using=using,
  File "/usr/local/lib/python3.6/dist-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_celery_results/managers.py", line 129, in store_result
    defaults=fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
 File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?
```

**Comment by jmorel** [comment]
So the issue was that the scheduler didn't have access to the DB. I updated the related chart to give it access as well. I also added a log so that we have a trace of what happened.

**Pull request merged**
