### PR TITLE
Data samples order

### PR DESCRIPTION
**Pull request by jmorel**
:warning: In order for this PR to be merged, https://github.com/SubstraFoundation/substra-tools/pull/43 has to be merged first and the 0.7.0 release done.

With this change, the relative order of data samples is added to the command executed by the algo container during training.

### CODE REVIEW

**Comment by AurelienGasser** [comment]
@jmorel Wouldn't it be simpler to _always_ respect the order of datasamples?

In `prepare_materials`, we could create a `data_samples.json` file, with contents `subtuple['dataset']['keys']` (ordered list of keys). Substra-tools could read from that file and always respect the order (which is the order specified when creating the traintuple).

**Comment by samlesu** [comment]
> @jmorel Wouldn't it be simpler to _always_ respect the order of datasamples?
> 
> In `prepare_materials`, we could create a `data_samples.json` file, with contents `subtuple['dataset']['keys']` (ordered list of keys). Substra-tools could read from that file and always respect the order (which is the order specified when creating the traintuple).

I think that's already the case in this PR: the backend always set the data samples order. 

As this change is not backward compatible (the backend won't work with a previous version of substratools) I think it would be better to simplify the current substratools interface: have an argument specifying the data sample folder names (or paths) to load in the correct order (IMO substratools should not have to list the subfolders of the rootfolder).

**Comment by jmorel** [comment]
Actually there is one place where this PR doesn't enforce data samples order: for testtuples.

As for the interface with substra-tools, my reasoning was that adding an extra argument would allow the new substra tools to work with earlier versions of the backend, which could be nice for environments that can't be updated easily.

And about the json file, while I do agree that it could be simpler that having an extra long command (is there a limit to the size of a command btw?) it would introduce a second way of sending instructions to substra tools. In that case wouldn't it be better to remove all commands args and just populate a json file with all information?

**Comment by samlesu** [comment]
> Actually there is one place where this PR doesn't enforce data samples order: for testtuples.
> 
> As for the interface with substra-tools, my reasoning was that adding an extra argument would allow the new substra tools to work with earlier versions of the backend, which could be nice for environments that can't be updated easily.
> 
> And about the json file, while I do agree that it could be simpler that having an extra long command (is there a limit to the size of a command btw?) it would introduce a second way of sending instructions to substra tools. In that case wouldn't it be better to remove all commands args and just populate a json file with all information?

+1 for the json file (or yaml?), either use a single file for all parameters or use only command arguments. I do think using a file will make things easier to maintain, but I don't think it should be done in this PR.

I think we should focus now on code simplicity/maintainability rather than on compatibility but that's my personal point of view.

**Comment by AurelienGasser** [comment]
@jmorel Thanks for the details! 

I don't have a strong opinion about files v.s. argument, my concern was more about the duplication of information about which data samples to use.

> I think it would be better to simplify the current substratools interface: have an argument specifying the data sample folder names (or paths) to load in the correct order (IMO substratools should not have to list the subfolders of the rootfolder).

+1, I think this would make sense.

**Comment by jmorel** [comment]
@AurelienGasser @samlesu Done!

**Review by AurelienGasser — APPROVED** [review]
LGTM

**Comment by AurelienGasser** [comment]
@jmorel FYI there's a test failing. Probably a case of adding `keys` to a test dataset.

**Comment by jmorel** [comment]
Thanks @AurelienGasser, there was an incomplete feature, it's fixed!

**Review by Kelvin-M — APPROVED** [review]

**Review by samlesu — APPROVED** [review]

**Comment by jmorel** [comment]
Hello @AurelienGasser, I'm very happy to report that the tests are passing! (there was a bug following the rebase on master).

**Pull request merged**
