### PR TITLE
Add unecessary directories to dockerignore

### PR DESCRIPTION
**Pull request by Kelvin-M**
Speed up docker build for Docker for Mac

### CODE REVIEW

**Comment by samlesu** [comment]
> Speed up docker build for Docker for Mac

This PR will speed up docker builds for all OS ?

**Comment by Kelvin-M** [comment]
> > Speed up docker build for Docker for Mac
> 
> This PR will speed up docker builds for all OS ?

I don't know, as I cannot test on a linux :)

**Comment by Kelvin-M** [comment]
But I don't think so, as DockerForMac send a context to its VM to build the image

**Comment by samlesu** [comment]
Makes sense, thanks.

**Pull request merged**
