### PR TITLE
fix: skaffold profile three orgs

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1705

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by ThibaultFy** [comment]
/e2e --tests docs

To test, these are the e2e tests that are using this profile

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
Ok, so we have the `three-orgs` profile that does not support the skaffold last version, while the other profiles are not compatible with the previous version. Which skaffold version should be supported?

**Comment by ThibaultFy** [comment]
> Ok, so we have the `three-orgs` profile that does not support last version from skaffold, while the other profiles are not compatible with the previous version. Which skaffold version should be supported?

I guess the latest possible ? Is it possible to upgrade the three orgs profile to match the latest skaffold ?

**Pull request closed without merging**
