### PR TITLE
Fix crash when trying to save identical trunk/head models

### PR DESCRIPTION
**Pull request by AurelienGasser**
For a composite traintuple, if the head and the trunk out models are identical, the saving fails.
﻿
That's because not only do the two models have the same composite traintuple key (expected), they ALSO have the same value.

This PR adds a salt to avoid pkhash conflicts in that case.

### CODE REVIEW

**Comment by AurelienGasser** [comment]
Actually, this approach would be a breaking change. 

1. The pkhash calculation algorithm also needs to be updated in `get_and_put_local_model_content`

https://github.com/SubstraFoundation/substra-backend/blob/19ec017d26f5c58d50e8e8300b2b961e41b94fd3/backend/substrapp/tasks/tasks.py#L158-L160

2. Any existing deployment with composite traintuples in the ledger would lead to potential crashes

`get_and_put_local_model_content` expects the pkhash algorithm to be constant. (see code above)

With the proposed change, the new pkhash algorithm (with the salt) would be different from the old algorithm (without the salt). 

So assets saved in the ledger with the old algorithm would be not be usable on a backend using the new algorithm.

**Comment by Kelvin-M** [comment]
I think it was a good way to solve this issue ! It is difficult here to keep compatibility. We can do that by using old and new pkhash strategy if we need to keep retro-compatibility

**Comment by samlesu** [comment]
I also think this a good solution !
Correct me if I'm wrong, but AFAIK a change in the pkhash generation is not a blocking point.

**Comment by Kelvin-M** [comment]
> I also think this a good solution !
> Correct me if I'm wrong, but AFAIK a change in the pkhash generation is not a blocking point.

Depends if we support retro-compatibility

**Comment by AurelienGasser** [comment]
@Kelvin-M 

> We can do that by using old and new pkhash strategy if we need to keep retro-compatibility

Great idea, that would do it. We would need a timeline for deprecation (a future version when we'll stop accepting the old pkhash), but we can keep supporting both for the time being.

**Pull request closed without merging**
