### PR TITLE
Remove orderer configuration from substra backend

### PR DESCRIPTION
**Pull request by Kelvin-M**
Companion PR : https://github.com/SubstraFoundation/hlf-k8s/pull/17

### CODE REVIEW

**Comment by AurelienGasser** [comment]
@Kelvin-M did you try running the e2e tests?

**Comment by Kelvin-M** [comment]
@AurelienGasser What do you mean by e2e tests ?
I only run populate on docker and skaffold setup !

**Comment by AurelienGasser** [comment]
I mean [these tests](https://github.com/SubstraFoundation/substra-tests) :)

**Comment by AurelienGasser** [comment]
I was asking about the tests to make sure the changes had been tested before I do the review :)

**Comment by Kelvin-M** [comment]
@GuillaumeCisco Do you haver some time to review this PR and the companions https://github.com/SubstraFoundation/hlf-k8s/pull/17

and https://github.com/SubstraFoundation/hlf-k8s/pull/16 (be careful this one need surely to be updated along https://github.com/SubstraFoundation/substra-backend/pull/55 final decision)

**Comment by GuillaumeCisco** [comment]
I don't have time to test it, but it is ok for me

**Pull request merged**
