### PR TITLE
feat: make image builder timeout configurable

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1660

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — APPROVED** [review]
Maybe we need a change fragment for the backend too? It's kind of a new feature...?

**Pull request merged**
