### PR TITLE
renamed to snake_case

### PR DESCRIPTION
**Pull request by hzk120**
Changed file names from camelCase to snake_case

### CODE REVIEW

**Comment by Kelvin-M** [comment]
Thank you for your contribution.
As we recently move to open source, CI was not set/merged when you do your fork (https://github.com/SubstraFoundation/substra-backend/pull/19) !
Can you rebase your work on the current `dev` to trigger the CI !

@GuillaumeCisco @inalgnu Did someone test this work manually to see if nothing is broken ?

**Comment by Kelvin-M** [comment]
@hzk120 🖖 Is it possible for you to rebase your work on current `dev` branch :) ?

**Comment by hzk120** [comment]
@Kelvin-M Ok I will do that :)

**Comment by Kelvin-M** [comment]
@hzk120  Have you some time to rebase this branch on master ? :)

**Comment by hzk120** [comment]
@Kelvin-M Sorry got busy with some other things,will try to finish it in the coming week if that's acceptable :)

**Comment by Kelvin-M** [comment]
Closed because of #95 which use and complete this PR

**Pull request closed without merging**
