### PR TITLE
Retry ledger call on phantom read conflict

### PR DESCRIPTION
**Pull request by jmorel**
@inalgnu and I ran into a new error from the ledger: "PHANTOM READ CONFLICT".

This PR adds a retry in case this error is returned by the ledger. The status code attached to the error is really just a placeholder, we didn't take the time to properly investigate what the code should be. If you have an opinion about it please feel free to share!

### CODE REVIEW

**Comment by GuillaumeCisco** [comment]
Looks like an issue in substra design.
Something with a range query seems to have been updated between chaincode execution and commit.

More information: https://stackoverflow.com/questions/51950726/hyperledger-phantom-read-conflict-vs-mvcc-read-conflict

**Comment by Kelvin-M** [comment]
I agree with Guillaume that it may come from a substra design. @jmorel Do we have an issue in the chaincode to expose this problem ?
Nevertheless, we should handle this issue :) Thank you @jmorel for this update =)

**Comment by jmorel** [comment]
I'm sorry, I don't have a specific scenario to generate these errors, they just "appears" while trying to add A LOT of tuples to the platform.

**Comment by samlesu** [comment]
I do agree with @Kelvin-M and @GuillaumeCisco. It will be interesting to investigate more and it could be caused by a wrong design.

As a quick term solution, a retry should fix it.

**Pull request merged**
