### PR TITLE
Fail fast: remove evaluation for train like tuples

### PR DESCRIPTION
**Pull request by samlesu**
Tasks:
- [x] views: remove link between train like tuples and objective
- [x] views: add link between testtuple and objective
- [x] views: update compute plan accordingly (remove global objective_key and define it at the tuple level)
- [x] compute: remove evaluation step for train like tuples
- [x] update populate

Companion PRs:
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/50)
- [substra](https://github.com/SubstraFoundation/substra/pull/52)
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/25)

### CODE REVIEW

**Comment by samlesu** [comment]
> The "create" method for train like tuple views still reference the objective_key

Good catch, thanks!

**Comment by jmorel** [comment]
Since computePlanID and rank have been added to testtuples in the related chaincode PR could add it here as well?

**Comment by samlesu** [comment]
> This function should be refactored too much if/else that make it complicated to understand
> https://github.com/SubstraFoundation/substra-backend/blob/979d73be5b1671de4c5a3b84d72aca69c721c522/backend/substrapp/tasks/tasks.py#L550#L715

Yes, you're completely right, this function and I think the whole module is too complicated to read and to maintain. I think the whole module requires a big refactoring and this refactoring should be done separately. This could be done later, a refactoring session is scheduled in the coming weeks.

Would that be ok for you?

**Comment by Kelvin-M** [comment]
Adding another if seems to add more complexity to this function.
As this function could be refactor without border effect, I think it could be done in this PR.

**Comment by samlesu** [comment]
> Adding another if seems to add more complexity to this function.
> As this function could be refactor without border effect, I think it could be done in this PR.

Correct me if I'm wrong, but no `if` clause has been added to the function pointed in your link (that is to say the `_do_task()` function).
An `if` clause has been added to the `prepare_materials()` function but this one is pretty simple as it has been slightly refactored recently.

Most of the if/else clauses of the function `_do_task()` have been added in an another PR. In my opinion, review should be related to the scope of the reviewed PR only.

**Comment by Kelvin-M** [comment]
@samlesu https://github.com/SubstraFoundation/substra-backend/pull/63/files#diff-1c7f95fdd9883397a5489522f326ccb7R691 (line 691 is between line 550 and line 715)

**Comment by samlesu** [comment]
> @samlesu https://github.com/SubstraFoundation/substra-backend/pull/63/files#diff-1c7f95fdd9883397a5489522f326ccb7R691 (line 691 is between line 550 and line 715)

Yes. This change is not adding an `if` clause, it was already there. It is changing the line

```python
if tuple_type == AGGREGATETUPLE_TYPE:  # skip evaluation
```

to:

```python
if tuple_type != TESTTUPLE_TYPE:  # skip evaluation
```

**Comment by Kelvin-M** [comment]
A modification in git is considered as a removal and a addition :)

**Comment by samlesu** [comment]
> Isn't the compute plan in the populate broken here? It shouldn't have a global algo key as input anymore but each traintuple should have its own algo. It doesn't looks like it is the case.

Indeed, good catch! But that's as far as I know not related to this PR.

**Comment by camillemarini** [comment]
Hello @Kelvin-M @samlesu @inalgnu Let's keep this refactoring for another PR :-) I think we need this PR merged as soon as possible.

**Pull request merged**
